CREATE TABLE IF NOT EXISTS "tags" (key TEXT PRIMARY KEY, value BLOB)
CREATE TABLE IF NOT EXISTS "last_active" (key TEXT PRIMARY KEY, value BLOB)
CREATE TABLE IF NOT EXISTS "email" (key TEXT PRIMARY KEY, value BLOB)
CREATE TABLE IF NOT EXISTS "tweets" (key TEXT PRIMARY KEY, value BLOB)
