FROM debian:bullseye

RUN apt-get update && apt-get install -y python3 python3-pip python3-sklearn 

COPY ./requirements.armv7.txt *.py /app/

RUN pip install --no-cache-dir  --upgrade -r /app/requirements.armv7.txt

COPY . /app/
EXPOSE 5000

WORKDIR /app
